version: "3.9"

services:
   db:
      image: postgres:14-alpine
      environment:
         - POSTGRES_USER=root
         - POSTGRES_PASSWORD=secret
         - POSTGRES_DB=github_api_db
      env_file:
         - .env
      ports:
         - 5439:5432
      restart: on-failure
 
   api:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         -  "8080:8080"
      environment:
         - DATABASE_USER=${DATABASE_USER}
         - DATABASE_PASSWORD=${DATABASE_PASSWORD}
         - DATABASE_NAME=${DATABASE_NAME}
         - DATABASE_HOST=${DATABASE_HOST}
      env_file:
         - .env
      depends_on:
         - db
      command: [ "/app/main" ]